#!/bin/bash
mysql -u root <<EOF
CREATE DATABASE wpdb;
CREATE USER '{$MYSQL_USER}'@'10.12.69.2' IDENTIFIED by '{$MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON wpdb.* TO '{$MYSQL_USER}'@'10.12.69.2';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '{$MYSQL_ROOT_PASSWORD}';
EOF